### ISSUE TITLE
Backup phrase not displayed correctly

### ISSUE THREAD

**Issue by jbergh** [tokenbrowser/token-ios-client#182]
When trying to store the backup phrase it does not correctly show on the screen (see screenshot) while "Copy phrase to clipboard" works. I am using Version 1.0 and iOS 10.3.1.
![screenshot2017-04](https://cloud.githubusercontent.com/assets/27806697/25223256/3233e7ac-25bb-11e7-98f3-8e42e9bdfbe3.png)

**Comment by roberthein** [comment]
This happened when the same word would occur twice the backup phrase. This is fixed now.
