### ISSUE TITLE
Scan Users' wallet QR code but no wallet address visible to confirm?

### ISSUE THREAD

**Issue by jclarkv** [tokenbrowser/token-ios-client#187]
iOS version
In Settings-->Your Profile and tap QR code icon in upper right. 
QR code appears on iPhone screen as expected (I presume this QR code represents the wallet address within Tokey).  When scanned by another wallet app (Exodus on OS X, in my case) the address field is filled by the wallet app, but I have no way to display actual wallet address **in Token** to confirm the two addresses match.

**Comment by Elland** [comment]
We might be adding a plain text display of your wallet address for this purpose. The formats/use-cases for the contents of this QR code are still being worked out, but for the time being it has been updated to a https URL as we want to avoid people accidentally sending mainnet ETH to testnet addresses.
