### ISSUE TITLE
iOS issue with rating screen and typing review 

### ISSUE THREAD

**Issue by pablanopete** [tokenbrowser/token-ios-client#190]
when opening the review section in iOS the submit button cannot be pressed without pressing outside of the input screen to the side. See image. popup keyboard covers up 'submit' button. 
![ratebug](https://cloud.githubusercontent.com/assets/18363825/25315249/f9745abe-2817-11e7-87e5-52ecfb609f47.png)

**Comment by Elland** [comment]
@roberthein should be simple enough have the view positioning respond to keyboard changes, right?

**Comment by roberthein** [comment]
It should already respond to keyboard changes, something broke.

**Comment by Elland** [comment]
Fixed: https://github.com/tokenbrowser/token-ios-client/pull/193.
