### ISSUE TITLE
issue with active apps after adding 'contacts'

### ISSUE THREAD

**Issue by pablanopete** [tokenbrowser/token-ios-client#191]
in iOS after adding new 'contacts' the list of active apps or selecting any apps disappears from the menu. see image 

![activeappbug](https://cloud.githubusercontent.com/assets/18363825/25315340/3e4ac76c-2819-11e7-89d6-a7cf0e7258f3.png)

**Comment by Elland** [comment]
@pablanopete I haven't been able to reproduce it. Could you give us more detailed steps or perhaps a recording? 👍

**Comment by pablanopete** [comment]
It seems to have not done this after resetting the app. I'll update if happens again or I can get a recording
