### ISSUE TITLE
backup phrase issue

### ISSUE THREAD

**Issue by pablanopete** [tokenbrowser/token-ios-client#192]
iOS after already backing up the security backup phrase, it seems that adding new 'contacts' causes the error of starting the backup process over. see image.

![backupissue](https://cloud.githubusercontent.com/assets/18363825/25315393/e00acd7c-2819-11e7-9511-48137428bd21.png)

**Comment by Elland** [comment]
@pablanopete Hey, thanks for the issue, but I couldn't reproduce it locally. Could you give us more detailed steps or maybe a recording?

**Comment by roberthein** [comment]
@Elland I reproduced this by:
1. verify the backup phrase
2. kill the app
3. go back to settings

result: app says backup phrase is not verified.
