### ISSUE TITLE
Crash when tapping Add App

### ISSUE THREAD

**Issue by roberthein** [tokenbrowser/token-ios-client#214]
Crashes on `YapDatabaseConnection`, line number 1909.
Crash appeared in distribution build after tapping **Add App** for **Token Together** in **Browse** section.

`*** Terminating app due to uncaught exception 'YapDatabaseException', reason: 'YapDatabaseConnection[0x102f247d0] - deadlock detection'`

**Comment by roberthein** [comment]
This happens always when trying to add a second app, never the first.
Here's the stack-trace:

![screen shot 2017-05-04 at 14 08 52](https://cloud.githubusercontent.com/assets/474246/25704856/753f4110-30db-11e7-8f24-10162ce9e050.png)

**Comment by Elland** [comment]
Great. Debugging!

**Comment by Elland** [comment]
Should be fixed by #213

**Comment by roberthein** [comment]
✨
