### ISSUE TITLE
Wrong content offset in messages.

### ISSUE THREAD

**Issue by roberthein** [tokenbrowser/token-ios-client#215]
After dismissing a UIAlertView in a chat, the content insets at the bottom of the collection view are off.

![img_0760](https://cloud.githubusercontent.com/assets/474246/25703768/38aaf82e-30d7-11e7-866a-8273acd6b764.PNG)

**Comment by Elland** [comment]
I think we can close this now, yes? @roberthein @yuliaveres

**Comment by yuliaveres** [comment]
i think yes,
