### ISSUE TITLE
Browse search bar wrong top offset

### ISSUE THREAD

**Issue by yuliaveres** [tokenbrowser/token-ios-client#218]
When started typing into searchbar on Browse page,
and trying to scroll up-down, 
- searchBar is getting cropped;
- top offset is not ok
![img_5797](https://cloud.githubusercontent.com/assets/27722554/25705731/9a87ae1e-30de-11e7-8203-718e9edc3e9d.PNG)
![img_5798](https://cloud.githubusercontent.com/assets/27722554/25705779/c25b98a6-30de-11e7-98d0-a620e0775cca.PNG)

**Comment by marijnschilling** [comment]
Maybe it's totally unrelated, but I had a similar (yet opposite) problem this morning. Where the scrollView used an offset of 20px on the top while it shouldn't 🙈 : https://github.com/bakkenbaeck/Lift/pull/17

I needed to set `automaticallyAdjustsScrollViewInsets` on the viewController to false.
