### ISSUE TITLE
App freezes completely sometimes

### ISSUE THREAD

**Issue by roberthein** [tokenbrowser/token-ios-client#222]
1. delete Token from iPhone
2. install Token
3. Select **Week in Ethereum** in **Browse**
4. **Add App**
5. Tap **Favorites**
`app freezes completely`

**Comment by yuliaveres** [comment]
😨

**Comment by Elland** [comment]
The previous adding contact fix apparently also fixes this. Marking as fixed. We can re-open if it happens again.

**Comment by roberthein** [comment]
Nice 👌
