### ISSUE TITLE
Balance shows as zero in Me section

### ISSUE THREAD

**Issue by dkofodimos** [tokenbrowser/token-ios-client#234]
I attach a couple of pics for user @sofopo. You can see balance shows as 0 in the Me section while it is clear from the other pic that balance is 29.68 USD

![img_3242](https://cloud.githubusercontent.com/assets/10214333/26007803/428757ca-376c-11e7-9aa1-d003b4a34e19.PNG)
![img_3243](https://cloud.githubusercontent.com/assets/10214333/26007802/4283c542-376c-11e7-8135-2eb1e0afa65f.PNG)

**Comment by Elland** [comment]
@dkofodimos thanks! I noticed the same earlier today, so #233 fixes it. 🚀
