### ISSUE TITLE
Upgraded to Version 1.1 -> my balance now shows as 0

### ISSUE THREAD

**Issue by dkofodimos** [tokenbrowser/token-ios-client#245]
User @dkof   I just upgraded to version 1.1 a few minutes ago and my balance now shows as 0.0 but I definitey had balance (around 50 USD) before the upgrade.

**Comment by Elland** [comment]
Is all other data intact? Username, contacts?

**Comment by dkofodimos** [comment]
To be more specific it is shown as 0 in the Me tab

**Comment by dkofodimos** [comment]
Yes, the other data seems intact. When I go to messages I see the balance (now around 100 usd)

**Comment by Elland** [comment]
@dkofodimos it's possible it's an issue with the exchange rate API failing for some reason, and then it falls back to `0`. 🤔

**Comment by Elland** [comment]
@dkofodimos so only in the `Me` page the balance is 0?

**Comment by dkofodimos** [comment]
Yes

**Comment by Elland** [comment]
I see. Thanks, I'll look into it!

**Comment by clamprecht** [comment]
I can confirm same issue.  Balance is 0 on Me page but is non-zero and correct in the chat page.

**Comment by Elland** [comment]
@clamprecht @dkofodimos if you send/receive money, does the value update at all?

**Comment by Elland** [comment]
This has been fixed. New building coming soon. 👍

**Comment by dkofodimos** [comment]
Great, thanks. Looking forward to the next build
