### ISSUE TITLE
iOS client crashes when I tap to go to Scan page

### ISSUE THREAD

**Issue by clamprecht** [tokenbrowser/token-ios-client#246]
Every time I tap on the Scan button in the bottom menu, the app just exits immediately. Version 1.1, iOS 10.3.1 on iPhone 6S.

**Comment by clamprecht** [comment]
I just fixed this by going to iOS settings -> Privacy -> Camera, and enabling Token to access the camera.  So maybe the fix is just to show an error message like "Please allow Token to access the camera" instead of crashing.

**Comment by Elland** [comment]
Fixed in #248. Thanks!
