### ISSUE TITLE
Image messages not rendering

### ISSUE THREAD

**Issue by jamespeerless** [tokenbrowser/token-ios-client#278]
If you send a message with an image attachment it does not render the image unless you back out and come back into the chat.

With chat open, receive a message with image attachment, displays small empty white box (no image), back out to Recent, go back into the chat and image is rendered fine.

**Comment by Elland** [comment]
That's not a common issue we've encountered, but it has been fixed on the current codebase. A new update including those fixes is forthcoming. 💪🏽

**Comment by Elland** [comment]
New message UI is now on RC 1.2.
