### ISSUE TITLE
Few apps reply to initial messages

### ISSUE THREAD

**Issue by alex-miller-0** [tokenbrowser/token-ios-client#279]
I installed Token on the first night it was released and the experience was great. Some time later (after updates), I have found that almost none of the apps will reply to my messages. 

The exceptions are the default ones (adbot, tokenbot, and Week in Ethereum). Everything else is 
completely non-responsive.

I know these apps are written by 3rd party developers, but it seems suspicious that I can't get a single one to do anything. Also, I believe the SOFA protocol has a default fallback response so this doesn't make any sense.

**Comment by Elland** [comment]
Hi @alex-miller-0, Bots are all self-hosted. That means that if you register a new bot, run it locally from your computer and turn the process or the computer off, that bot is now offline, so it won't respond to any message. To keep a bot running at all times, it needs to be hosted on an always-on computer (heroku, linode). So yeah, bots are just users, so if they go offline, you can't talk to them.

**Comment by alex-miller-0** [comment]
Makes sense. Have you considered a keep-alive ping when a search is made so that users don't add deprecated apps?

**Comment by Elland** [comment]
We've been discussing something along those lines, yes.
